name: ItemUltra
main: xyz.rainbowpunk.itemultra.ItemUltra
version: 0.0.1
api-version: 1.16
commands:
  vault:
    description: Opens the Ultra Vault.
  unobtainium:
    description: Obtain the unobtainable.